### ISSUE TITLE
Downloads does not contain any links for Docs & Demos

### ISSUE THREAD

**Issue by GadgetSteve** [wxWidgets/wxPyWeb#2]
The downloads page does not include any links to the download site for Offline Documentation and the Demos package. 

Note that these downloads are _currently_ hosted at [SourceForge](https://sourceforge.net/projects/wxpython/files/wxPython4/extras/) in the extras project.

**Comment by RobinD42** [comment]
There was a link to the new extras site, but I've emphasized the docs and demos a bit more there.
