### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by david-hughes** [wxWidgets/wxPyWeb#3]
otherwise known as wxPython 0.2, also with some help from Edward Zimmerman. The mailing list announcement of that release is archived
here.  
-->
https://wxpython.org/pages/history/%5Bhttp:/www.google.com/groups?selm=PA.95Jul27032244%40ok.tekla.fi&oe=UTF-8

David Hughes

**Comment by RobinD42** [comment]
Thanks. Fixed in update coming shortly. Unfortunately I havn't yet found any message archives that still go back that far. Oh well.
