### ISSUE TITLE
Extraneous backtick on https://docs.wxpython.org/app_overview.html

### ISSUE THREAD

**Issue by brettcannon** [wxWidgets/wxPyWeb#4]
https://docs.wxpython.org/app_overview.html shows ```wx.Window.Close`()``` which suggests there's an extra tick typo.

(I would fix this myself but for the life of me I can't find the file that this file comes from.)

**Comment by swt2c** [comment]
Looks like this was fixed by: https://github.com/wxWidgets/Phoenix/commit/1f5fe1e3981d39b16380cd54b27488dba75d9357
