### ISSUE TITLE
Looks like the etg file needs updated to add that line.

### ISSUE THREAD

**Issue by cutiezang3l** [wxWidgets/wxPyWeb#6]
Looks like the etg file needs updated to add that line.
Still exists in new Scintilla Docs
https://www.scintilla.org/ScintillaDoc.html#Notifications

_Originally posted by @Metallicow in https://github.com/wxWidgets/Phoenix/issues/1613#issuecomment-619467959_

**Comment by Metallicow** [comment]
Thank you for acknowledging.
